options(warn = 2)
register_path <- "docs/roadmap/post-0.2.0/roadmap-decisions.csv"
baseline_sha <- "9865434038b1c7dbbe4da3959341d27d15029ee6"
current <- read.csv(register_path, check.names = FALSE, stringsAsFactors = FALSE)
baseline_text <- system2("git", c("show", paste0(baseline_sha, ":", register_path)), stdout = TRUE)
baseline <- read.csv(textConnection(paste(baseline_text, collapse = "\n")), check.names = FALSE, stringsAsFactors = FALSE)
stopifnot(nrow(baseline) == 39L, nrow(current) == 40L)
stopifnot(identical(current[seq_len(39L), ], baseline))
stopifnot(!anyDuplicated(current$decision_id))
for (id in sprintf("DEC-%03d", 37:40)) stopifnot(sum(current$decision_id == id) == 1L)
stopifnot(!("DEC-041" %in% current$decision_id))
stopifnot(identical(current$decision_id[[40L]], "DEC-040"))
stopifnot(identical(current$status[[40L]], "APPROVED — IMPLEMENTED/CERTIFIED C-EXIT"))
gov <- read.csv("dev/hardening/governance-register/c-govr-certification.csv", check.names = FALSE, stringsAsFactors = FALSE)
stopifnot(any(gov[[1L]] == "CEXIT-GOV-001" & gov[[2L]] == "CLOSED BY C-GOVR"))
stopifnot(any(gov[[1L]] == "CEXIT-SPEC-001" & gov[[2L]] == "CLOSED BY C-GOVR"))
stopifnot(file.exists("inst/architecture/oceancube-certification-evidence-policy-v1.md"))
ignore <- readLines(".Rbuildignore", warn = FALSE)
stopifnot(any(grepl("dev", ignore, fixed = TRUE)))
cat("C_EXIT_GOVERNANCE_VALIDATOR: PASS\n")
cat("DECISION_ROWS=40\nNEXT_AVAILABLE=DEC-041\n")
