library(oceancube)
message('Discrete slicing')
p <- system.file('examples','cube_slice.R',package='oceancube')
stopifnot(nzchar(p), file.exists(p))
source(p, local=new.env(parent=globalenv()))
message('PASS')
library(oceancube)
message('Rectangular cropping')
p <- system.file('examples','cube_crop.R',package='oceancube')
stopifnot(nzchar(p), file.exists(p))
source(p, local=new.env(parent=globalenv()))
message('PASS')
