library(oceancube)
message('Ordered transect')
p <- system.file('examples','cube_transect.R',package='oceancube')
stopifnot(nzchar(p), file.exists(p))
source(p, local=new.env(parent=globalenv()))
message('PASS')
library(oceancube)
message('Event linkage')
p <- system.file('examples','refactor_link_events_backend.R',package='oceancube')
stopifnot(nzchar(p), file.exists(p))
source(p, local=new.env(parent=globalenv()))
message('PASS')
