library(oceancube)
message('Polygon mask')
p <- system.file('examples','cube_mask.R',package='oceancube')
stopifnot(nzchar(p), file.exists(p))
source(p, local=new.env(parent=globalenv()))
message('PASS')
