library(oceancube)
message('Area, thickness and volume')
p <- system.file('examples','cube_geometry_weights.R',package='oceancube')
stopifnot(nzchar(p), file.exists(p))
source(p, local=new.env(parent=globalenv()))
message('PASS')
